### ISSUE TITLE
[Feat] 허브 API 

### ISSUE THREAD

**Issue by yell2023** [Logistics-system-project/Hub-service#1]
## Description
> 설명

물류 관리 및 배송 시스템에서의 허브 생성 및 조회, 수정, 삭제 등의 허브 관리 기능

## Requirements
> 기능 구현을 위한 요구사항
- 스파르타 물류의 허브는 17개로 허브의 위치는 고정
- 허브 엔티티에 is_delete 필드를 추가하여 논리적으로 삭제 관리
- 사용자 권한에 따라 허브 관리 권한 제한
- 허브 정보가 자주 변경되지 않으며 반복적으로 조회될 가능성이 있음으로 허브 정보 캐싱

## Estimated Duration
12/9(월) ~ 12/10 (화) [2일]

## Todo
> 기능 구현을 위한 할 일 작성
- [x] 허브 entity 생성
- [x] 허브 생성 기능 구현
- [x] 허브 목록 조회 기능 구현
- [x] 허브 상세 조회 기능 구현
- [x] 허브 수정 기능 구현
- [x] 허브 삭제 기능 구현
- [x] 구현 기능 테스트
